name: Update S3 Variable

on:
  push:
    branches:
      - main 

jobs:
  update-s3-docker:
    runs-on: ubuntu-latest

    env:
      BUILD_NUMBER: ${{ github.run_number }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1


      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: gunjanchhabra1
          password: ${{ secrets.SECRET_TOKEN }}

      - name: access s3 bucket 
        run: | 
          aws s3 cp s3://demo-bucket-acs/version.json .
          jq --arg build_number "$BUILD_NUMBER" '.image_version = $build_number' version.json > updated-version.json
          aws s3 cp updated-version.json s3://demo-bucket-acs/version.json 
          aws s3 cp s3://demo-bucket-acs/version.json - | cat -

      - name: get json file and get the version
        run: |
           aws s3 cp s3://demo-bucket-acs/version.json ./version.json
           $new_version=$(jq -r '.image_version' ./version.json)

      - name: Build the new Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}:$new_version .
          docker push ghcr.io/${{ github.repository }}:$new_version
