name: Update S3 Variable

on:
  push:
    branches:
      - main 

jobs:
  update-s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: access s3 bucket 
        run: | 
          aws s3 cp s3://demo-bucket-acs/version.json .
          # Use jq to update the JSON key's value
          jq '.image_version = "0.0.0"' version.json > updated-version.json
          aws s3 cp updated-version.json s3://demo-bucket-acs/version.json    #Upload the updated JSON file back to S3
          aws s3 cp s3://demo-bucket-acs/version.json - | cat -
          
      # - name: Update JSON Variable
      #   run: |
      #     pip3 install requests boto3
      #     python main.py
      #     # echo '{ "image_version": "2.0" }' >> version.json
      #     # # Upload the updated JSON file to S3
      #     # aws s3 cp version.json s3://demo-bucket-acs/version.json
        # working-directory: ${{ github.workspace }}

      # - name: Commit Changes to GitHub
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "actions@github.com"
      #     git add version.json
      #     git commit -m "Update image_version in version.json"
      #     git push
      #   working-directory: ${{ github.workspace }}